# Generated by Django 5.2 on 2025-05-05 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='Если нужно, вы можете изменить дату записи вручную', verbose_name='Дата записи'),
        ),
    ]
